# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75030b259be7f6440a382718e3fe1c5e34bebbc38ed99f8729f92001b609b15e2e1399e26e10e4d17a6cac7ef93c7bee539d3a21fb373a36ba9ee4759ed3955e

test:
  secret_key_base: f3f057b251b61b55245c140ac185ed081816f55c34c420c93fbe159fea0ecbc68541592f851d904a7875d2dc9de61895927c6daf1d97d6d2886ab15392eb154b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
